apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: smart-devops
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: ghcr.io/dulanilakmali/smart-devops-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - secretRef:
                name: backend-secrets

          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "5000"

            - name: DB_PATH
              value: "/app/data/devops_assistant.sqlite"

          volumeMounts:
            - name: backend-storage
              mountPath: /app/data

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-data